import { Press_Start_2P } from 'next/font/google'

import './globals.css'
import Navbar from '../components/navbar'
const inter = Press_Start_2P({ subsets: ['latin'], weight:['400'] })

export const metadata = {
  title: 'Online IDE',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar />
          {children}
      </body>
    </html>
  )
}
